version: "2"
services:
   elf:
     image: node:12.10.0
     user: node
     working_dir: /application
     volumes:
       - .:/application:cached
     ports:
       - 4200:4200
       - 9229:9229
     command: "yarn start --host=0.0.0.0"
